name: Build Feature Branch

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!fix/[0-9]+.[0-9]+.x'
      - '![0-9]+.x'
      - '!dependabot/**'

jobs:
  branch:
    uses: onecx/ci-java-lib/.github/workflows/cli-build-branch.yml@v1
    secrets: inherit
